In [2]:
import torch
x = torch.empty(5, 3)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[1.0497e+28, 4.5687e-41, 1.0497e+28],
        [4.5687e-41, 7.9011e+31, 5.2943e-14],
        [4.2904e+24, 3.6072e-14, 1.3563e-19],
        [2.6792e+20, 7.1774e+22, 4.3210e+27],
        [2.8068e+20, 3.9159e-02, 6.1400e+13]])


In [3]:
x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])


In [4]:
print(torch.cuda.is_available())


True


In [5]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!  


tensor([6.5000, 4.0000], device='cuda:0')
tensor([6.5000, 4.0000], dtype=torch.float64)


In [ ]:
import torch, torchvision
model = torchvision.models.resnet18(pretrained=False)


In [ ]:
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)
